### ISSUE TITLE
关于在哪里下载最新版本插件

### ISSUE THREAD

**Issue by 07-iceven** [SnowCherryServer/Snow-Motd#3]
我想知道在哪里下载最新版本的插件，MCBBS已经关服，我目前使用的是3.2版本，而最新版本是3.2.7。
![image](https://github.com/user-attachments/assets/4cb4c4f4-043e-49d2-9348-f4cf3c6dd5f4)

**Comment by mincHR549** [comment]
您好，由于3.2版本并未更新联网公告，所以导致您获取了错误的更新提示我倍感抱歉。
请前往QQ群：878379031 内可获取最新版插件
或请留下您的个人邮箱，我将会给您发送新版插件
